name: Deploy to Production

on:
    push:
        branches: [main]

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: "8.2"
                  extensions: mbstring, xml, ctype, iconv, intl
                  tools: composer

            - name: Setup deployment
              run: |
                  echo "${{ secrets.ENV_FILE }}" > .env
                  mkdir -p ~/.ssh
                  echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
                  chmod 600 ~/.ssh/id_ed25519
                  ssh-keyscan -H ${{ secrets.DEPLOY_HOST }} >> ~/.ssh/known_hosts
              env:
                  DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
                  DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
                  DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}

            - name: Install dependencies and deploy
              run: |
                  composer install --no-interaction --prefer-dist --optimize-autoloader --no-scripts
                  ./vendor/bin/dep deploy:unlock prod || true
                  ./vendor/bin/dep deploy prod -v
              env:
                  DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
                  DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
                  DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
